<h4> Importing the Dependencies <h4>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.ensemble import IsolationForest

In [2]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv("C:\\Users\\DELL\\Downloads\\archive (20)\\creditcard.csv")

In [3]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [5]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [6]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [7]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

<h7>This Dataset is highly unblanced

0 --> Normal Transaction

1 --> fraudulent transaction<h7>

In [8]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [9]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [10]:
# statistical measures of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [11]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [12]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

<h7> Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 492 <h7>

In [13]:
legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [14]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [15]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
70071,53695.0,-0.733484,1.323697,0.896669,0.056342,-0.108253,-0.557580,0.300540,0.486839,-0.580249,...,-0.189240,-0.580180,0.083767,0.023198,-0.204192,0.103573,0.135160,0.032543,9.99,0
228239,145415.0,-0.916330,-0.540563,1.489470,-2.344397,0.027767,-0.394099,-0.294329,0.204111,-0.961290,...,0.511167,1.295731,-0.186003,-0.359706,0.159328,-0.119889,0.321033,0.184662,52.12,0
181062,124809.0,-0.952963,-0.048046,-0.517778,0.402821,1.738284,-1.457065,0.754535,-0.103439,-0.007030,...,0.104166,0.063019,0.285071,0.898629,-0.322415,-0.374148,0.156935,0.282804,99.93,0
42683,41199.0,1.168636,0.669297,0.228544,2.768742,0.121112,-0.136120,0.011669,0.033738,-0.258075,...,-0.396550,-1.041449,0.001731,-0.269233,0.431495,-0.147642,0.021894,0.051353,9.68,0
165744,117626.0,-0.050533,1.056208,-1.116186,-0.253714,0.493929,-0.804691,0.628035,0.301949,-0.405089,...,0.373925,0.960751,-0.117862,-0.587606,-0.313912,-0.142249,-0.021772,0.027338,42.81,0

In [16]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [17]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [18]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,93877.540650,-0.031513,-0.005072,0.037829,-0.060133,0.003461,-0.067910,-0.029185,0.031818,0.023943,...,-0.048879,0.030713,-0.062059,-0.012871,-0.030586,0.033811,-0.016011,0.014664,-0.009777,78.498293
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

<h7>We'll do anomaly detection using isolation forest and feature engineering to improve the data quality<h7>

In [19]:
model = IsolationForest(n_estimators=100, contamination=0.2, max_features=1.0)
model.fit(new_dataset[['Amount']])

IsolationForest(contamination=0.2)

In [20]:
new_dataset['anomalies_sccores']=model.decision_function(new_dataset[['Amount']])
new_dataset['anomaly']=model.predict(new_dataset[['Amount']])
new_dataset.head(20)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V23,V24,V25,V26,V27,V28,Amount,Class,anomalies_sccores,anomaly
70071,53695.0,-0.733484,1.323697,0.896669,0.056342,-0.108253,-0.557580,0.300540,0.486839,-0.580249,...,0.083767,0.023198,-0.204192,0.103573,0.135160,0.032543,9.99,0,0.044846,1
228239,145415.0,-0.916330,-0.540563,1.489470,-2.344397,0.027767,-0.394099,-0.294329,0.204111,-0.961290,...,-0.186003,-0.359706,0.159328,-0.119889,0.321033,0.184662,52.12,0,0.005627,1
181062,124809.0,-0.952963,-0.048046,-0.517778,0.402821,1.738284,-1.457065,0.754535,-0.103439,-0.007030,...,0.285071,0.898629,-0.322415,-0.374148,0.156935,0.282804,99.93,0,0.049325,1
42683,41199.0,1.168636,0.669297,0.228544,2.768742,0.121112,-0.136120,0.011669,0.033738,-0.258075,...,0.001731,-0.269233,0.431495,-0.147642,0.021894,0.051353,9.68,0,0.044131,1
165744,117626.0,-0.050533,1.056208,-1.116186,-0.253714,0.493929,-0.804691,0.628035,0.301949,-0.405089,...,-0.117862,-0.587606,-0.313912,-0.142249,-0.021772,0.027338,42.81,0,0.021037,1
280404,169511.0,1.933798,0.505730,-0.742581,3.783564,0.651463,0.418300,0.123195,-0.042109,-0.736497,...,0.083350,0.590129,0.201899,0.071337,-0.027375,-0.043988,7.56,0,0.034516,1
241449,151031.0,0.150995,0.795090,-1.756355,-0.893702,1.721896,0.880227,0.634730,0.651945,-0.726672,...,-0.009166,-0.657018,-0.504062,0.617906,-0.116191,-0.097443,0.76,0,0.092415,1
209336,137514.0,-1.072529,0.605578,0.108154,-0.529731,0.652586,-1.117162,1.196490,-0.158508,0.353366,...,-0.023653,-0.160810,0.144549,-0.071707,0.234459,0.256029,97.01,0,0.025166,1
67020,52328.0,1.007483,-0.106975,0.134349,1.227912,-0.489891,-0.947815,0.303969,-0.200541,0.139773,...,-0.193832,0.367717,0.605093,-0.337356,-0.016775,0.039189,126.71,0,-0.029085,-1
168413,119216.0,2.173123,-1.046783,-0.872707,-1.133563,-0.595801,0.173342,-1.085212,0.057894,-0.106805,...,-0.015652,-1.109048,-0.040488,-0.036687,0.009474,-0.067487,19.95,0,0.031206,1
271651,164677.0,2.066172,0.092108,-1.886098,0.188152,0.706353,-0.279737,0.069809,-0.056344,0.273067,...,0.267847,-0.004382,-0.224764,0.184377,-0.067395,-0.045620,1.79,0,0.070435,1
74365,55539.0,-1.278108,0.321740,0.627704,-3.752696,0.024798,-1.405640,0.372627,0.405346,1.217878,...,-0.227820,0.019226,0.361643,-1.228423,0.254049,0.055361,6.05,0,0.022123,1
215900,140270.0,-0.738708,-0.081687,-0.121043,-0.600091,1.028510,-0.584985,1.263739,-0.174380,0.214335,...,0.189637,-0.607886,0.337277,-0.087922,-0.005310,-0.150508,169.33,0,-0.066106,-1
40506,40269.0,-2.769069,0.600346,0.296308,1.666014,-0.535891,-0.172940,-0.862735,1.362119,-0.809510,...,-0.682868,0.279241,-0.076985,-0.258355,-0.370341,-0.434295,40.25,0,0.024581,1
129054,78935.0,-0.522037,-0.180855,1.351876,-1.371785,-1.245249,-0.378738,-0.882833,0.427841,-2.766961,...,0.196605,0.031442,-0.645773,-0.363420,0.064590,0.045936,19.35,0,0.035374,1
273966,165792.0,-1.288923,2.334051,1.323701,4.103376,-0.095335,1.395135,-0.524166,1.193326,-1.923135,...,-0.152872,-1.112476,0.154909,0.285467,0.225901,0.089812,2.24,0,0.055740,1
44238,41856.0,0.474711,-2.332241,0.547216,-1.658287,-1.455335,1.277855,-0.848474,0.405807,0.923396,...,-0.068053,-0.586809,-0.153271,-0.031735,0.087675,0.079879,357.26,0,-0.093887,-1
31719,36487.0,-2.074815,1.971212,0.366958,-0.673527,-1.091228,-0.897938,-0.435505,1.377522,-0.415775,...,0.101730,0.547578,-0.097061,0.278720,0.133792,0.105694,1.00,0,0.115673,1
278783,168429.0,2.270875,-1.310344,-0.884546,-1.444077,-1.350925,-1.093149,-0.924373,-0.349459,-1.316221,...,0.211419,0.044579,-0.157293,-0.166778,0.009517,-0.047491,30.00,0,0.039836,1
137209,82066.0,1.235088,0.366776,0.443775,0.769193,-0.528785,-1.259835,0.093234,-0.225064,0.008720,...,0.170295,0.671731,0.173290,0.074271,-0.022410,0.033993,0.89,0,0.100562,1

In [21]:
#Number of Anamoalies
# Count the number of -1 values in the 'anomaly' column
num_anomalies = (new_dataset['anomaly'] == -1).sum()

print("Number of anomalies:", num_anomalies)

Number of anomalies: 195

In [22]:
# Remove entries with anomaly label -1
cleaned_dataset = new_dataset[new_dataset['anomaly'] != -1]

# Display the cleaned dataset
print(cleaned_dataset)

            Time        V1        V2        V3        V4        V5        V6  \
70071    53695.0 -0.733484  1.323697  0.896669  0.056342 -0.108253 -0.557580
228239  145415.0 -0.916330 -0.540563  1.489470 -2.344397  0.027767 -0.394099
181062  124809.0 -0.952963 -0.048046 -0.517778  0.402821  1.738284 -1.457065
42683    41199.0  1.168636  0.669297  0.228544  2.768742  0.121112 -0.136120
165744  117626.0 -0.050533  1.056208 -1.116186 -0.253714  0.493929 -0.804691
...          ...       ...       ...       ...       ...       ...       ...
274475  166028.0 -0.956390  2.361594 -3.171195  1.970759  0.474761 -1.902598
276071  166883.0  2.091900 -0.757459 -1.192258 -0.755458 -0.620324 -0.322077
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V23       V24       V25  \
70071   0.300540  0.486839 -0.580249  ...  0.083767  0.023198 -0.204192
228239 -0.294329  0.204111 -0.961290  ... -0.186003 -0.359706  0.159328
181062  0.754535 -0.103439 -0.007030  ...  0.285071  0.898629 -0.322415
42683   0.011669  0.033738 -0.258075  ...  0.001731 -0.269233  0.431495
165744  0.628035  0.301949 -0.405089  ... -0.117862 -0.587606 -0.313912
...          ...       ...       ...  ...       ...       ...       ...
274475 -0.055178  0.277831 -1.745854  ...  0.122458 -0.255650 -0.619259
276071 -1.082511  0.117200 -0.140927  ...  0.142007  0.592615 -0.196143
280143 -1.413170  0.248525 -1.127396  ... -0.145640 -0.081049  0.521875
280149 -2.234739  1.210158 -0.652250  ...  0.190944  0.032070 -0.739695
281674  0.223050 -0.068384  0.577829  ... -0.072173 -0.450261  0.313267

             V26       V27       V28  Amount  Class  anomalies_sccores  \
70071   0.103573  0.135160  0.032543    9.99      0           0.044846
228239 -0.119889  0.321033  0.184662   52.12      0           0.005627
181062 -0.374148  0.156935  0.282804   99.93      0           0.049325
42683  -0.147642  0.021894  0.051353    9.68      0           0.044131
165744 -0.142249 -0.021772  0.027338   42.81      0           0.021037
...          ...       ...       ...     ...    ...                ...
274475 -0.484280  0.683535  0.443299   39.90      1           0.026104
276071 -0.136676  0.020182 -0.015470   19.95      1           0.031206
280143  0.739467  0.389152  0.186637    0.76      1           0.092415
280149  0.471111  0.385107  0.194361   77.89      1           0.010195
281674 -0.289617  0.002988 -0.015309   42.53      1           0.021664

        anomaly
70071         1
228239        1
181062        1
42683         1
165744        1
...         ...
274475        1
276071        1
280143        1
280149        1
281674        1

[789 rows x 33 columns]

In [23]:
cleaned_dataset.shape

(789, 33)

<h7>Splitting the data into Features & Targets<h7>

In [24]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [25]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
70071    53695.0 -0.733484  1.323697  0.896669  0.056342 -0.108253 -0.557580
228239  145415.0 -0.916330 -0.540563  1.489470 -2.344397  0.027767 -0.394099
181062  124809.0 -0.952963 -0.048046 -0.517778  0.402821  1.738284 -1.457065
42683    41199.0  1.168636  0.669297  0.228544  2.768742  0.121112 -0.136120
165744  117626.0 -0.050533  1.056208 -1.116186 -0.253714  0.493929 -0.804691
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V22       V23       V24  \
70071   0.300540  0.486839 -0.580249  ... -0.580180  0.083767  0.023198
228239 -0.294329  0.204111 -0.961290  ...  1.295731 -0.186003 -0.359706
181062  0.754535 -0.103439 -0.007030  ...  0.063019  0.285071  0.898629
42683   0.011669  0.033738 -0.258075  ... -1.041449  0.001731 -0.269233
165744  0.628035  0.301949 -0.405089  ...  0.960751 -0.117862 -0.587606
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ... -0.319189  0.639419 -0.294885
280143 -1.413170  0.248525 -1.127396  ...  0.028234 -0.145640 -0.081049
280149 -2.234739  1.210158 -0.652250  ...  0.834108  0.190944  0.032070
281144 -2.208002  1.058733 -1.632333  ... -0.269209 -0.456108 -0.183659
281674  0.223050 -0.068384  0.577829  ... -0.295135 -0.072173 -0.450261

             V25       V26       V27       V28  Amount  anomalies_sccores  \
70071  -0.204192  0.103573  0.135160  0.032543    9.99           0.044846
228239  0.159328 -0.119889  0.321033  0.184662   52.12           0.005627
181062 -0.322415 -0.374148  0.156935  0.282804   99.93           0.049325
42683   0.431495 -0.147642  0.021894  0.051353    9.68           0.044131
165744 -0.313912 -0.142249 -0.021772  0.027338   42.81           0.021037
...          ...       ...       ...       ...     ...                ...
279863  0.537503  0.788395  0.292680  0.147968  390.00          -0.124696
280143  0.521875  0.739467  0.389152  0.186637    0.76           0.092415
280149 -0.739695  0.471111  0.385107  0.194361   77.89           0.010195
281144 -0.328168  0.606116  0.884876 -0.253700  245.00          -0.070256
281674  0.313267 -0.289617  0.002988 -0.015309   42.53           0.021664

        anomaly
70071         1
228239        1
181062        1
42683         1
165744        1
...         ...
279863       -1
280143        1
280149        1
281144       -1
281674        1

[984 rows x 32 columns]

In [26]:
print(Y)

70071     0
228239    0
181062    0
42683     0
165744    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

<h7>Split the data into Training data & Testing Data<h7>

In [27]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [28]:
print(X.shape, X_train.shape, X_test.shape)

(984, 32) (787, 32) (197, 32)

Model Training

Logistic Regression

In [29]:
model = LogisticRegression()

In [30]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

LogisticRegression()

Model Evaluation

Accuracy Score

In [31]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [32]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.940279542566709

In [33]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [34]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9086294416243654